### DISCUSSION TITLE
https://starter.obytes.com/ci-cd/app-releasing-process/

### DISCUSSION THREAD

**Discussion by giscus** [obytes/react-native-template-obytes#249] [Docs Comments]
# https://starter.obytes.com/ci-cd/app-releasing-process/

How to release your app to the App Store and Google Play

https://starter.obytes.com/ci-cd/app-releasing-process/

**Comment by eduance** [comment]
You guys are life savers!

**Comment by hamzaCarswitch** [comment]
I am using pnpm as recommended in template, but I am getting below error on my eas build, and it is failing

Running "yarn install" in /home/expo/workingdir/build directory
error This project's package.json defines "packageManager": "yarn@pnpm@9.12.3". However the current global version of Yarn is 1.22.22.
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.

**Reply by M-Farih** [reply]
Make sure pnpm-lock.yaml is committed to your repo. EAS Build uses it to correctly choose the package manager.
Hope this saves someone else hours of debugging!

**Reply by Kane-dplabs** [reply]
update ur eas-cli

**Comment by 504knight** [comment]
Y'all recommend not pushing the .env files to github. However, when I do that and add the SpicyPizza/create-envfile@v2.0 step to my EAS Build QA workflow it breaks saying that the environment variables are missing.

Maybe I'm missing something. Here's that part of my workflow and the error I get in GitHub actions.

```
name: EAS QA Build (Android & IOS) (EAS)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  Build:
    name: EAS QA Build (Android & IOS) (EAS)
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: Create .env.development file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: true
          envkey_SECRET_KEY: ${{ secrets.DEVELOPMENT_SECRET_KEY }}
          envkey_VAR_NUMBER: ${{ secrets.VAR_NUMBER }}
          envkey_API_URL: ${{ secrets.API_URL }}
          file_name: .env.development

      - name: Create .env.staging file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: true
          envkey_SECRET_KEY: ${{ secrets.STAGING_SECRET_KEY }}
          envkey_VAR_NUMBER: ${{ secrets.VAR_NUMBER }}
          envkey_API_URL: ${{ secrets.API_URL }}
          file_name: .env.staging

      - name: ⏱️ EAS Build
        uses: ./.github/actions/eas-build
        with:
          APP_ENV: staging
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}
          IOS: false # TODO: set as true when IOS account is ready
```
```
[02:25:02] → ❌ Invalid environment variables: {
  SECRET_KEY: [ 'Required' ],
  API_URL: [ 'Required' ],
  VAR_NUMBER: [ 'Expected number, received nan' ]
} 
❌ Missing variables in .env.development file, Make sure all required variables are defined in the .env.development file. 
💡 Tip: If you recently updated the .env.development file and the error still persists, try restarting the server with the -c flag to clear the cache.

[02:25:02] → Error: Error reading Expo config at /home/runner/work/UltimateFamilyFinance/UltimateFamilyFinance/app.config.ts:

Invalid environment variables, Check terminal for more details 
Error: Error reading Expo config at /home/runner/work/UltimateFamilyFinance/UltimateFamilyFinance/app.config.ts:

Invalid environment variables, Check terminal for more details 
    at Object.<anonymous> (/home/runner/work/UltimateFamilyFinance/UltimateFamilyFinance/env.js:142:9)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/home/runner/work/UltimateFamilyFinance/UltimateFamilyFinance/app.config.ts:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at requireFromString (/home/runner/work/UltimateFamilyFinance/UltimateFamilyFinance/node_modules/require-from-string/index.js:28:4)
```
