### ISSUE TITLE
release production version on Bitrise

### ISSUE THREAD

**Issue by iamhaaamed** [obytes/react-native-template-obytes#152]
How can we release production version on Bitrise? I have added an env variable with APP_ENV key and production value, but it is still releasing development version.

**Comment by yjose** [comment]
I am not that familiar with Bitrise, but we just need to make sure you run the correct pre-build before the build. Here is an example we use with GitHub Actions.

```yaml
name: QA Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  Build:
    name: Android & IOS QA Build
    runs-on: ubuntu-latest
    steps:
      - name : 📦 Checkout project repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 📦 Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: 📦 Restore Project Dependencies (node_modules)
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 📦 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install Project Dependencies
        run: yarn install --immutable

      - name: ⚙️ Run Prebuild
        run: yarn prebuild:staging

      - name: 📱 Run Android Build
        run: yarn build:staging:android --non-interactive --no-wait --message "QA ${{ github.event.release.tag_name }}"

      - name: 📱 Run IOS Build
        run: yarn build:staging:ios --non-interactive --auto-submit --no-wait --message "QA ${{ github.event.release.tag_name }}"
```
